PUT http://localhost:8080/events/1
Content-Type: application/json

{
  "name": "Updated Event",
  "description": "Updated Event Description",
  "location": "Updated Event Location",
  "dateTime": "2021-12-31T23:59:59.999Z"
}